# Generated by Django 5.2.15 on 2026-06-16 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AppPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="نام دسترسی")),
                (
                    "codename",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="کد دسترسی"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("hr", "منابع انسانی"),
                            ("finance", "مالی"),
                            ("it", "فناوری اطلاعات"),
                            ("admin", "مدیریتی"),
                            ("report", "گزارش"),
                            ("other", "سایر"),
                        ],
                        default="other",
                        max_length=50,
                        verbose_name="دسته\u200cبندی",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="توضیحات")),
            ],
            options={
                "verbose_name": "دسترسی",
                "verbose_name_plural": "دسترسی\u200cها",
            },
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="نام شرکت")),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="نام انگلیسی"
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="logos/", verbose_name="لوگو"
                    ),
                ),
                (
                    "registration_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="شماره ثبت"
                    ),
                ),
                ("website", models.URLField(blank=True, verbose_name="وب\u200cسایت")),
                ("description", models.TextField(blank=True, verbose_name="توضیحات")),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین ویرایش"),
                ),
            ],
            options={
                "verbose_name": "شرکت",
                "verbose_name_plural": "شرکت\u200cها",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="نام نقش")),
                (
                    "code",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="کد نقش"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="توضیحات")),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
            ],
            options={
                "verbose_name": "نقش",
                "verbose_name_plural": "نقش\u200cها",
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "ایجاد"),
                            ("update", "ویرایش"),
                            ("delete", "حذف"),
                            ("assign", "تخصیص"),
                            ("move", "جابجایی"),
                        ],
                        max_length=20,
                        verbose_name="عملیات",
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(max_length=50, verbose_name="نوع موجودیت"),
                ),
                ("entity_id", models.IntegerField(verbose_name="شناسه موجودیت")),
                (
                    "entity_name",
                    models.CharField(max_length=200, verbose_name="نام موجودیت"),
                ),
                ("description", models.TextField(verbose_name="توضیحات")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ"),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="انجام\u200cدهنده",
                    ),
                ),
            ],
            options={
                "verbose_name": "لاگ عملیات",
                "verbose_name_plural": "لاگ\u200cهای عملیات",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="نام واحد")),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="کد واحد"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="توضیحات")),
                (
                    "manager_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="نام مدیر"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                ("order", models.IntegerField(default=0, verbose_name="ترتیب")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین ویرایش"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="departments",
                        to="org_chart.company",
                        verbose_name="شرکت",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="org_chart.department",
                        verbose_name="واحد والد",
                    ),
                ),
            ],
            options={
                "verbose_name": "واحد سازمانی",
                "verbose_name_plural": "واحدهای سازمانی",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "personnel_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="شماره پرسنلی"
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="نام")),
                (
                    "last_name",
                    models.CharField(max_length=100, verbose_name="نام خانوادگی"),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="ایمیل"),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="تلفن"),
                ),
                (
                    "national_id",
                    models.CharField(blank=True, max_length=20, verbose_name="کد ملی"),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="avatars/",
                        verbose_name="تصویر",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "hire_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاریخ استخدام"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین ویرایش"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employee",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر سیستم",
                    ),
                ),
            ],
            options={
                "verbose_name": "پرسنل",
                "verbose_name_plural": "پرسنل",
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="عنوان پست")),
                (
                    "code",
                    models.CharField(max_length=50, unique=True, verbose_name="کد پست"),
                ),
                ("description", models.TextField(blank=True, verbose_name="توضیحات")),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                ("order", models.IntegerField(default=0, verbose_name="ترتیب")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین ویرایش"),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="positions",
                        to="org_chart.department",
                        verbose_name="واحد",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="org_chart.position",
                        verbose_name="پست والد",
                    ),
                ),
            ],
            options={
                "verbose_name": "پست سازمانی",
                "verbose_name_plural": "پست\u200cهای سازمانی",
                "ordering": ["order", "title"],
            },
        ),
        migrations.CreateModel(
            name="PositionRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="position_roles",
                        to="org_chart.position",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="org_chart.role"
                    ),
                ),
            ],
            options={
                "verbose_name": "نقش پست",
                "verbose_name_plural": "نقش\u200cهای پست",
                "unique_together": {("position", "role")},
            },
        ),
        migrations.AddField(
            model_name="position",
            name="roles",
            field=models.ManyToManyField(
                blank=True,
                through="org_chart.PositionRole",
                to="org_chart.role",
                verbose_name="نقش\u200cها",
            ),
        ),
        migrations.CreateModel(
            name="UserPosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(default=True, verbose_name="پست اصلی"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                ("start_date", models.DateField(verbose_name="تاریخ شروع")),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="تاریخ پایان"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_positions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="تخصیص\u200cدهنده",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_positions",
                        to="org_chart.employee",
                        verbose_name="پرسنل",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_positions",
                        to="org_chart.position",
                        verbose_name="پست",
                    ),
                ),
            ],
            options={
                "verbose_name": "تخصیص پرسنل",
                "verbose_name_plural": "تخصیص\u200cهای پرسنل",
            },
        ),
        migrations.CreateModel(
            name="RolePermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="org_chart.apppermission",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_permissions",
                        to="org_chart.role",
                    ),
                ),
            ],
            options={
                "verbose_name": "دسترسی نقش",
                "verbose_name_plural": "دسترسی\u200cهای نقش",
                "unique_together": {("role", "permission")},
            },
        ),
        migrations.CreateModel(
            name="UserPermissionOverride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "override_type",
                    models.CharField(
                        choices=[("grant", "اعطای دسترسی"), ("deny", "سلب دسترسی")],
                        max_length=10,
                        verbose_name="نوع",
                    ),
                ),
                ("reason", models.TextField(blank=True, verbose_name="دلیل")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ایجادکننده",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permission_overrides",
                        to="org_chart.employee",
                        verbose_name="پرسنل",
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="org_chart.apppermission",
                        verbose_name="دسترسی",
                    ),
                ),
            ],
            options={
                "verbose_name": "استثنای دسترسی",
                "verbose_name_plural": "استثناهای دسترسی",
                "unique_together": {("employee", "permission")},
            },
        ),
    ]
